name: Build Rust project
on: [pull_request]
jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [1.36.0, stable, nightly]
    steps:
    - uses: actions/checkout@master
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Run build
      run: cargo build
  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [1.36.0, stable, nightly]
    steps:
    - uses: actions/checkout@master
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Run build
      run: cargo build

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [1.36.0, stable, nightly]
    steps:
    - uses: actions/checkout@master
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Install libudev
      run: sudo apt-get update && sudo apt-get install -y libudev-dev
    - name: Run build
      run: cargo build
